spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:p6spy:oracle:thin:@yggcv8zldawsd5fk_medium?TNS_ADMIN=C:/wallet
    username: dev
    password: Jaeyeong1234
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

server:
  port: 9090

decorator:
  datasource:
    p6spy:
      enable: false

logging:
  level:
    p6spy: INFO

file:
  upload:
    path: C:/upload	   